#!/usr/bin/env python


import rospy
import math
from sensor_msgs.msg import Range
from std_msgs.msg import String
from geometry_msgs.msg import Twist


max_speed=0.4
speed=float
y=float
elevation=1.5

def stream(data):
	pub=rospy.Publisher('atilay/cmd_vel', Twist, queue_size=10)
	distance=data.range
	y=distance-elevation
	twist = Twist()
	if y >= 1:
		twist.linear.z=-0.4
	elif y <= -1:
		twist.linear.z=0.4
	else:
		if y<0:
			speed=-(y/15.625)
			speed=speed**(1./2.)
		elif y >= 0:
			speed=(y/15.625)
			speed=speed**(1./2.)
			speed=-speed
		twist.linear.z=speed
		if y > -0.1 and y < 0.1:
			twist.linear.z=0
	

        rospy.loginfo(twist)
        pub.publish(twist)
        	
		

def streamer():
	rospy.init_node('streamer', anonymous=True)

	rospy.Subscriber("atilay/sonar", Range, stream)

	rate = rospy.Rate(100)

	while not rospy.is_shutdown():
		rate.sleep()	

if __name__ == '__main__':
    try:
        streamer()
    except rospy.ROSInterruptException:
        pass
